version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      # - npm ci
      - cd apps/api
      - npm install -g pnpm
      - pnpm install


  build:
    commands:
      - echo Packaging artifacts...
      # - zip -r output.zip .
      - cd apps/api
      - pnpm build

artifacts:
  base-directory: ./apps/api/dist  # or a specific folder like "build-output"
  files:
    - '**/*'
  discard-paths: no   # Keep folder structure intact
# artifacts:
#   files:
#     # - output.zip
#     - ./*
#   discard-paths: yes
